name: .NET Framework build

on:
  push:
    branches: [ v8/contrib ]
  pull_request:
    branches: [ v8/contrib ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    - name: Restore packages
      run: nuget restore .\src\umbraco.sln
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    - name: Build with MSBuild
      run: msbuild .\src\umbraco.sln -p:Configuration=Release
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    - name: Code analysis
      run: |
        curl -O https://www.shiftleft.io/download/sl-latest-windows-x64.zip
        powershell -Command "& {Expand-Archive sl-latest-windows-x64.zip -DestinationPath . ;}"
        .\sl analyze --app Umbraco-GH --wait --cpg --csharp --dotnet-framework --csharp2cpg-args "-l info" .\src\umbraco.sln
        sleep 10
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true 
